name: penetration-app
base: core18
version: '1.0'
summary: Penetration App
description: A GUI application for penetration testing.

grade: stable
confinement: strict

parts:
  app:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - libgtk-4-dev
      - gir1.2-gtk-4.0
      - gir1.2-adw-1
      - gir1.2-notify-0.7
      - libgdk-pixbuf2.0-dev

apps:
  penetration-app:
    command: main.py
    plugs:
      - unity7
