name: penetration-app
version: '1.0'
summary: A penetration testing tool with a GUI
description: |
  This application provides a graphical user interface (GUI) for a penetration testing tool.

grade: devel
confinement: devmode

base: core22

parts:
  desktop-gtk4:
    plugin: nil
    build-packages:
      - gir1.2-gtk-4.0
      - gir1.2-gdkpixbuf-2.0

  app:
    source: .
    plugin: python
    python-version: python3
    source-type: local
    source-subdir: .
    stage-packages:
      - python3-gi
    after: [desktop-gtk4]

apps:
  penetration-app:
    command: python3 src/main.py
    plugs:
      - x11
      - desktop
      - wayland
      - browser-support

plugs:
  x11:
    interface: x11
    allow-x11: true

  desktop:
    interface: desktop
    desktop: [unity7, gnome-shell, cinnamon, pantheon, budgie-remix]

  wayland:
    interface: wayland
    allow-apps: ['penetration-app']

  browser-support:
    interface: browser-support
    allow-sandbox: true
    allow-snap-apps:
      - chromium
      - firefox
